import type { Course } from "@/types";

/** Erwachsenen- und Kinderkurse. Quelle: prototype-v2. */
export const COURSES: Course[] = [
  // ---------------------------------------------------------------- Erwachsene
  {
    slug: "aquarell-fuer-einsteiger",
    audience: "erwachsene",
    title: { de: "Aquarell für Einsteiger", en: "Watercolour for Beginners" },
    category: { de: "Malen", en: "Painting" },
    teaser: {
      de: "Lerne die Grundlagen der Aquarellmalerei, Farben, Wasser und Loslassen.",
      en: "Learn the basics of watercolour, colour, water and letting go.",
    },
    description: {
      de: "In diesem Kurs tauchst du Schritt für Schritt in die Aquarellmalerei ein. Wir beginnen bei den Grundlagen, wie sich Farbe und Wasser verhalten, wie du Verläufe legst und mit dem Zufall spielst. Ganz ohne Druck, in einer kleinen Gruppe und mit viel individueller Begleitung.",
    },
    takeaway: {
      de: "Zwei bis drei fertige Aquarelle, ein Gefühl für Farbe und Wasser und die Gewissheit, dass du das kannst.",
    },
    price: "CHF 280",
    meta: [
      { label: { de: "Zielgruppe" }, value: { de: "Erwachsene" } },
      { label: { de: "Level" }, value: { de: "Anfänger" } },
      { label: { de: "Dauer" }, value: { de: "6× 2 Stunden" } },
      { label: { de: "Termine" }, value: { de: "Di 18–20 Uhr" } },
      { label: { de: "Gruppe" }, value: { de: "max. 8 Personen" } },
      { label: { de: "Material" }, value: { de: "inklusive" } },
      { label: { de: "Start" }, value: { de: "14. September" } },
    ],
    schedule: { de: "Di 18–20 Uhr" },
    start: { de: "Start 14. September" },
    availability: { de: "noch 3 Plätze" },
    instructor: "lena-baumann",
    faq: [
      {
        q: { de: "Brauche ich Vorkenntnisse?" },
        a: { de: "Nein. Der Kurs ist für absolute Einsteiger gedacht, wir beginnen ganz vorne." },
      },
      {
        q: { de: "Muss ich Material mitbringen?" },
        a: { de: "Nein, alles Material ist inklusive. Bring einfach gute Laune mit." },
      },
      {
        q: { de: "Was, wenn ich einen Termin verpasse?" },
        a: { de: "Kein Problem, melde dich kurz, wir finden eine Lösung." },
      },
    ],
    color: "teal",
  },
  {
    slug: "zeichnen-grundlagen",
    audience: "erwachsene",
    title: { de: "Zeichnen Grundlagen", en: "Drawing Fundamentals" },
    category: { de: "Zeichnen", en: "Drawing" },
    teaser: {
      de: "Linie, Licht und Schatten, die Basis, auf der alles andere aufbaut.",
      en: "Line, light and shadow, the base everything else builds on.",
    },
    description: {
      de: "Zeichnen kann jede und jeder lernen. In diesem Kurs übst du das Sehen und Umsetzen: Proportionen, Linienführung, Licht und Schatten. Mit Bleistift und einfachen Übungen entwickelst du Sicherheit und deinen eigenen Strich.",
    },
    takeaway: { de: "Ein Skizzenbuch voller Übungen und ein sicherer Strich." },
    price: "CHF 260",
    meta: [
      { label: { de: "Zielgruppe" }, value: { de: "Erwachsene" } },
      { label: { de: "Level" }, value: { de: "Anfänger" } },
      { label: { de: "Dauer" }, value: { de: "6× 2 Stunden" } },
      { label: { de: "Termine" }, value: { de: "Mo 18–20 Uhr" } },
      { label: { de: "Gruppe" }, value: { de: "max. 8 Personen" } },
      { label: { de: "Material" }, value: { de: "inklusive" } },
    ],
    schedule: { de: "Mo 18–20 Uhr" },
    instructor: "lena-baumann",
    color: "violet",
  },
  {
    slug: "handlettering-kalligrafie",
    audience: "erwachsene",
    title: { de: "Handlettering & Kalligrafie", en: "Hand-lettering & Calligraphy" },
    category: { de: "Papier", en: "Paper" },
    teaser: {
      de: "Schöne Buchstaben von Hand, verspielt, ruhig und meditativ.",
      en: "Beautiful letters by hand, playful, calm and meditative.",
    },
    description: {
      de: "Zwischen Kunst und Handwerk: Du lernst die Grundformen moderner Kalligrafie, den Umgang mit Brush-Pen und Feder und wie aus einzelnen Buchstaben stimmige Kompositionen werden. Ein Kurs, der Ordnung und Verspieltheit zusammenbringt.",
    },
    takeaway: { de: "Ein eigenes Alphabet, mehrere Letterings und viel Ruhe." },
    price: "CHF 240",
    meta: [
      { label: { de: "Zielgruppe" }, value: { de: "Erwachsene" } },
      { label: { de: "Level" }, value: { de: "Anfänger" } },
      { label: { de: "Dauer" }, value: { de: "5× 2 Stunden" } },
      { label: { de: "Termine" }, value: { de: "Do 19–21 Uhr" } },
      { label: { de: "Gruppe" }, value: { de: "max. 8 Personen" } },
      { label: { de: "Material" }, value: { de: "inklusive" } },
      { label: { de: "Start" }, value: { de: "21. September" } },
    ],
    schedule: { de: "Do 19–21 Uhr" },
    start: { de: "Start 21. September" },
    availability: { de: "noch 5 Plätze" },
    instructor: "mara-kunz",
    color: "coral",
  },
  {
    slug: "buchbinden-schachteln",
    audience: "erwachsene",
    title: { de: "Buchbinden & Schachteln", en: "Bookbinding & Boxes" },
    category: { de: "Papier", en: "Paper" },
    teaser: {
      de: "Aus Papier und Pappe werden Bücher, Hefte und kleine Schachteln.",
      en: "Paper and board become books, notebooks and little boxes.",
    },
    description: {
      de: "Ein handwerklicher Kurs für alle, die gern mit Papier arbeiten. Du bindest dein eigenes Notizbuch, lernst verschiedene Heftungen und fertigst eine passgenaue Schachtel. Präzise, ruhig und mit einem schönen Ergebnis zum Mitnehmen.",
    },
    takeaway: { de: "Ein selbst gebundenes Buch und eine Schachtel nach Mass." },
    price: "CHF 290",
    meta: [
      { label: { de: "Zielgruppe" }, value: { de: "Erwachsene" } },
      { label: { de: "Level" }, value: { de: "Anfänger" } },
      { label: { de: "Dauer" }, value: { de: "4× 3 Stunden" } },
      { label: { de: "Termine" }, value: { de: "Sa 10–13 Uhr" } },
      { label: { de: "Gruppe" }, value: { de: "max. 8 Personen" } },
      { label: { de: "Material" }, value: { de: "inklusive" } },
    ],
    schedule: { de: "Sa 10–13 Uhr" },
    instructor: "mara-kunz",
    color: "yellow",
  },
  {
    slug: "naehen-fuer-einsteiger",
    audience: "erwachsene",
    title: { de: "Nähen für Einsteiger", en: "Sewing for Beginners" },
    category: { de: "Textil", en: "Textile" },
    teaser: {
      de: "Von der Nähmaschine bis zum ersten fertigen Stück, ohne Berührungsängste.",
      en: "From the sewing machine to your first finished piece, no fear.",
    },
    description: {
      de: "Du wolltest schon immer nähen lernen? Hier startest du bei null: Nähmaschine einfädeln, gerade Nähte, einfache Schnitte. Am Ende nimmst du ein erstes selbst genähtes Stück mit nach Hause.",
    },
    takeaway: { de: "Sicherheit an der Nähmaschine und ein fertiges Projekt." },
    price: "CHF 300",
    meta: [
      { label: { de: "Zielgruppe" }, value: { de: "Erwachsene" } },
      { label: { de: "Level" }, value: { de: "Anfänger" } },
      { label: { de: "Dauer" }, value: { de: "5× 2.5 Stunden" } },
      { label: { de: "Termine" }, value: { de: "Mi 18–20:30 Uhr" } },
      { label: { de: "Gruppe" }, value: { de: "max. 6 Personen" } },
      { label: { de: "Material" }, value: { de: "inklusive" } },
      { label: { de: "Start" }, value: { de: "28. September" } },
    ],
    schedule: { de: "Mi 18–20:30 Uhr" },
    start: { de: "Start 28. September" },
    availability: { de: "wenige Plätze" },
    instructor: "mara-kunz",
    color: "green",
  },
  {
    slug: "cyanotypie-workshop",
    audience: "erwachsene",
    title: { de: "Cyanotypie-Workshop", en: "Cyanotype Workshop" },
    category: { de: "Experimentell", en: "Experimental" },
    teaser: {
      de: "Blaudruck mit Sonnenlicht, ein altes Verfahren, magisch einfach.",
      en: "Blueprint with sunlight, an old process, wonderfully simple.",
    },
    description: {
      de: "An einem Nachmittag lernst du das faszinierende Cyanotypie-Verfahren: Pflanzen, Formen und Fundstücke werden mit Sonnenlicht in tiefes Preussischblau gebannt. Du experimentierst frei und nimmst mehrere eigene Blaudrucke mit.",
    },
    takeaway: { de: "Mehrere fertige Cyanotypien und ein Faible fürs Ausprobieren." },
    price: "CHF 160",
    meta: [
      { label: { de: "Zielgruppe" }, value: { de: "Erwachsene" } },
      { label: { de: "Level" }, value: { de: "Alle" } },
      { label: { de: "Dauer" }, value: { de: "1× 4 Stunden" } },
      { label: { de: "Termine" }, value: { de: "Sa 13–17 Uhr" } },
      { label: { de: "Gruppe" }, value: { de: "max. 8 Personen" } },
      { label: { de: "Material" }, value: { de: "inklusive" } },
      { label: { de: "Datum" }, value: { de: "8. November" } },
    ],
    schedule: { de: "Sa 13–17 Uhr" },
    start: { de: "8. November" },
    isNew: true,
    instructor: "mara-kunz",
    color: "sky",
  },

  // -------------------------------------------------------------------- Kinder
  {
    slug: "kreativwerkstatt-klein",
    audience: "kinder",
    title: { de: "Kreativwerkstatt Mittwoch", en: "Wednesday Creative Workshop" },
    category: { de: "4–7 Jahre", en: "Ages 4–7" },
    teaser: {
      de: "Malen, basteln, matschen, die kleine Kreativrunde am Mittwoch.",
      en: "Painting, crafting, making a mess, the little Wednesday round.",
    },
    description: {
      de: "Eine geschützte kleine Runde für unsere Jüngsten. Hier darf ausprobiert, gematscht und gestaunt werden. Jede Woche ein neues Thema, immer mit viel Zeit fürs eigene Tempo.",
    },
    price: "CHF 20",
    priceNote: { de: "pro Mal" },
    meta: [
      { label: { de: "Alter" }, value: { de: "4–7 Jahre" } },
      { label: { de: "Wann" }, value: { de: "Mi 14–15:30 Uhr" } },
      { label: { de: "Gruppe" }, value: { de: "max. 8 Kinder" } },
      { label: { de: "Material" }, value: { de: "inklusive" } },
      { label: { de: "Mitbringen" }, value: { de: "nur gute Laune" } },
    ],
    schedule: { de: "Mi 14–15:30 Uhr" },
    instructor: "sofia-meier",
    color: "pink",
  },
  {
    slug: "kreativwerkstatt-gross",
    audience: "kinder",
    title: { de: "Kreativwerkstatt Mittwoch", en: "Wednesday Creative Workshop" },
    category: { de: "8–12 Jahre", en: "Ages 8–12" },
    teaser: {
      de: "Ausprobieren, was Spass macht, jede Woche ein neues Abenteuer.",
      en: "Try whatever's fun, a new adventure every week.",
    },
    description: {
      de: "In der grossen Kreativwerkstatt geht es um Ausdruck und Ausprobieren. Malen, drucken, bauen, gestalten, die Kinder wählen mit, wohin die Reise geht. Ohne Leistungsdruck, dafür mit viel Fantasie.",
    },
    takeaway: { de: "Selbstgemachte Werke und jede Menge Ideen für zu Hause." },
    price: "CHF 22",
    priceNote: { de: "pro Mal" },
    meta: [
      { label: { de: "Alter" }, value: { de: "8–12 Jahre" } },
      { label: { de: "Wann" }, value: { de: "Mi 14–16 Uhr" } },
      { label: { de: "Dauer" }, value: { de: "2 Stunden" } },
      { label: { de: "Gruppe" }, value: { de: "max. 8 Kinder" } },
      { label: { de: "Material" }, value: { de: "inklusive" } },
      { label: { de: "Mitbringen" }, value: { de: "nur gute Laune" } },
    ],
    schedule: { de: "Mi 14–16 Uhr" },
    instructor: "sofia-meier",
    faq: [
      {
        q: { de: "Muss mein Kind etwas können?" },
        a: { de: "Nein. Neugier reicht völlig, alles andere zeigen wir." },
      },
      {
        q: { de: "Was zieht mein Kind an?" },
        a: { de: "Etwas, das dreckig werden darf. Schürzen haben wir da." },
      },
      {
        q: { de: "Kann man einzeln kommen oder ist es ein Abo?" },
        a: { de: "Beides möglich, man kann einzelne Male buchen oder regelmässig dabei sein." },
      },
    ],
    color: "coral",
  },
  {
    slug: "samstagskurse",
    audience: "kinder",
    title: { de: "Samstagskurse", en: "Saturday Courses" },
    category: { de: "5–12 Jahre", en: "Ages 5–12" },
    teaser: {
      de: "Ein ganzer Vormittag zum Gestalten, ideal für ein kreatives Wochenende.",
      en: "A whole morning of making, a creative weekend treat.",
    },
    description: {
      de: "An ausgewählten Samstagen widmen wir uns einem grösseren Projekt: Von der Idee bis zum fertigen Werk. Genug Zeit, um richtig einzutauchen und stolz nach Hause zu gehen.",
    },
    price: "CHF 45",
    meta: [
      { label: { de: "Alter" }, value: { de: "5–12 Jahre" } },
      { label: { de: "Wann" }, value: { de: "ausgewählte Samstage" } },
      { label: { de: "Gruppe" }, value: { de: "max. 8 Kinder" } },
      { label: { de: "Material" }, value: { de: "inklusive" } },
    ],
    schedule: { de: "Samstags" },
    instructor: "sofia-meier",
    color: "yellow",
  },
  {
    slug: "ferienkurse",
    audience: "kinder",
    title: { de: "Ferienkurse", en: "Holiday Courses" },
    category: { de: "Ferien", en: "Holidays" },
    teaser: {
      de: "Kreative Ferientage mit Themen, Techniken und neuen Freundschaften.",
      en: "Creative holiday days with themes, techniques and new friends.",
    },
    description: {
      de: "In den Schulferien tauchen die Kinder mehrere Tage in ein Thema ein. Wir malen, basteln, experimentieren und haben einfach eine gute Zeit. Betreuung in kleinen Gruppen, Mittagspause inklusive.",
    },
    price: "CHF 120",
    priceNote: { de: "pro Ferienblock" },
    meta: [
      { label: { de: "Alter" }, value: { de: "5–12 Jahre" } },
      { label: { de: "Wann" }, value: { de: "in den Schulferien" } },
      { label: { de: "Gruppe" }, value: { de: "kleine Gruppen" } },
      { label: { de: "Material" }, value: { de: "inklusive" } },
    ],
    schedule: { de: "Schulferien" },
    instructor: "sofia-meier",
    color: "green",
  },
  {
    slug: "kindergeburtstage",
    audience: "kinder",
    title: { de: "Kindergeburtstage", en: "Kids' Birthdays" },
    category: { de: "Feiern", en: "Celebrate" },
    teaser: {
      de: "Feiert kreativ bei uns, Malen, Basteln und ein unvergesslicher Nachmittag.",
      en: "Celebrate creatively with us, an unforgettable afternoon.",
    },
    description: {
      de: "Ein Geburtstag im Atelier: Wir gestalten gemeinsam ein Thema, jedes Kind nimmt sein Werk mit nach Hause. Um Material, Aufbau und Aufräumen kümmern wir uns, ihr geniesst einfach.",
    },
    price: "auf Anfrage",
    meta: [
      { label: { de: "Alter" }, value: { de: "nach Absprache" } },
      { label: { de: "Dauer" }, value: { de: "ca. 2 Stunden" } },
      { label: { de: "Gruppe" }, value: { de: "nach Absprache" } },
      { label: { de: "Material" }, value: { de: "inklusive" } },
    ],
    ctaTo: "kontakt",
    color: "violet",
  },
  {
    slug: "stempel-selber-machen",
    audience: "kinder",
    title: { de: "Stempel selber machen", en: "Make Your Own Stamps" },
    category: { de: "Special", en: "Special" },
    teaser: {
      de: "Schnitzen, drucken, staunen, eigene Stempel für zu Hause.",
      en: "Carve, print, marvel, your own stamps to take home.",
    },
    description: {
      de: "In diesem kleinen Special schnitzen die Kinder eigene Stempel und drucken damit Karten, Papier und Stoffbeutel. Ein bisschen Technik, viel Fantasie und ein tolles Mitnehm-Set.",
    },
    price: "CHF 35",
    meta: [
      { label: { de: "Alter" }, value: { de: "6–12 Jahre" } },
      { label: { de: "Dauer" }, value: { de: "ca. 2 Stunden" } },
      { label: { de: "Gruppe" }, value: { de: "max. 8 Kinder" } },
      { label: { de: "Material" }, value: { de: "inklusive" } },
    ],
    instructor: "sofia-meier",
    color: "orange",
  },
];
